Added support for Lumen
spatie/laravel-cors pull request #14
Opened 2018-02-09 14:25 UTC by benjamincrozat

Hello,

Here is a very simple PR to add support for Lumen to this lovely little package. Not much to say, I don't think I forgot anything. I'd suggest to update the repo's description to mention Lumen to improve its discoverability.

2018-02-09 23:24 UTC, freekmurze requested changes

2018-02-09 23:24 UTC, freekmurze commented on src/CorsServiceProvider.php
> +    protected function isNotLumen()
I like positive conditions better. Could you rename this to `isLaravel`?

2018-02-09 23:24 UTC, freekmurze commented on src/CorsServiceProvider.php
> +        return ! preg_match('/lumen/i', app()->version());
Test for Laravel here.

2018-02-12 15:56 UTC, merged

2018-02-12 15:56 UTC, freekmurze commented
Thanks!

2018-02-12 16:17 UTC, MichaelDeBoey commented on src/CorsServiceProvider.php
> +        return ! preg_match('/lumen/i', app()->version());
Why not do a positive check and check for `laravel`?

2018-02-13 08:07 UTC, benjamincrozat commented
@MichaelDeBoey Because `app()->version()` on Laravel only returns the version number. Lumen does not. It returns `Lumen (5.6.0) (Laravel Components 5.6.*)` (something like that). It feels right to test it that way to me.